// Primitive data types in JavaScript include:
// Numbers - Integers, floats
// Strings - Any data under single quote, double quote or backtick quote
// Booleans - true or false value
// Null - empty value or no value
// Undefined - a declared variable without a value
// Symbol - A unique value that can be generated by Symbol constructor



// Non-primitive data types in JavaScript includes:
// Objects
// Arrays

console.log(typeof "Mayank kestwal") // Returns "string"
console.log(typeof 3) // Returns "number"
console.log(typeof true) // Returns "boolean"
console.log(typeof 2134234567889890123456789n) // Returns bigint
console.log(typeof undefined) // Returns "undefined"
console.log(typeof null) // Returns "object" (kind of a bug in JavaScript)
console.log(typeof Symbol('symbol')) // Returns Symbol


// object
var obj1 = {
    name: "Mayank"
}

// array    
var array1 = [1, 2, 3, 4]; 


console.log(typeof obj1)
console.log(typeof array1)

// var, let and const

// var is function scoped, let and const are block scope

function fly(){
    var activity = "flying"
    console.log(activity)
}

console.log(activity) // error


{
    let fname = "mayank kestwal"
    const age = 13
    console.log(fname) //error
    console.log(age)
}

console.log(fname) //error
console.log(age) // error